import '@/styles/globals.scss'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { locales, type ValidLocale } from '@/i18n/config'
import Header from '@/components/globals/Header/Header'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-poppins',
  display: 'swap',
})

export async function generateStaticParams() {
  return locales.map((lang) => ({ lang }))
}

interface RootLayoutProps {
  children: React.ReactNode
  params: {
    lang: ValidLocale
  }
}

export const metadata: Metadata = {
  title: 'Cappic Website',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, params: { lang } }: RootLayoutProps) {
  return (
    <html lang={lang} className={poppins.variable}>
      <body className={poppins.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
