import '@/styles/globals.scss'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Header from '@/components/globals/Header/Header'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-poppins',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Cappic Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html className={poppins.variable}>
      <body className={poppins.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
